### ISSUE TITLE
"If you have to contact me : go open a issue on one of my GitHub repos"

### ISSUE THREAD

**Issue by Dev5H0** [sopyb/Game-bot#1]
Yo, Sopy, suddenly when I want to message you on Discord, I noticed that you had disabled your account (according to your username at least); why? Did you quit? Will you come back? ;-;

**Comment by sopyb** [comment]
I'll be back, I'm just having my account dissabled for a while while I deal with my stuff

**Comment by sopyb** [comment]
If you hit me with a PM on Instagram DoimptSopy could provide more info. @Dev5H0

**Comment by MissHeda** [comment]
Hey sopy,
Just letting you know that we quarantined you on our server GirlsCord. due to you request.
We also opened a ticket where you can text us in when you are back so we can unquarantine you.
I really hope it's not to bad at the moment. I'm hella worried about you, stay strong sis.

Mia
